'use strict';

// INTERFACES
import { options_i } from 'interfaces/common';

// CONFIG
import config from '../config';

// UTILS
import UTILS_SERVICES from '../utils/services';

class service_settings_init {
  private readonly options: options_i;
  private readonly validator: any;

  private readonly cities: object[];
  private readonly districts: object[];
  private readonly neighbourhoods: object[];

  constructor(options: options_i) {
    this.options = options;
    this.validator = new UTILS_SERVICES.settings_validator_init(options);

    this.cities = [
      { name: 'adana', id: 1 },
      { name: 'adiyaman', id: 2 },
      { name: 'afyonkarahisar', id: 3 },
      { name: 'agri', id: 4 },
      { name: 'amasya', id: 5 },
      { name: 'ankara', id: 6 },
      { name: 'antalya', id: 7 },
      { name: 'artvin', id: 8 },
      { name: 'aydin', id: 9 },
      { name: 'balikesir', id: 10 },
      { name: 'bilecik', id: 11 },
      { name: 'bingol', id: 12 },
      { name: 'bitlis', id: 13 },
      { name: 'bolu', id: 14 },
      { name: 'burdur', id: 15 },
      { name: 'bursa', id: 16 },
      { name: 'canakkale', id: 17 },
      { name: 'cankiri', id: 18 },
      { name: 'corum', id: 19 },
      { name: 'denizli', id: 20 },
      { name: 'diyarbakir', id: 21 },
      { name: 'edirne', id: 22 },
      { name: 'elazig', id: 23 },
      { name: 'erzincan', id: 24 },
      { name: 'erzurum', id: 25 },
      { name: 'eskisehir', id: 26 },
      { name: 'gaziantep', id: 27 },
      { name: 'giresun', id: 28 },
      { name: 'gumushane', id: 29 },
      { name: 'hakkari', id: 30 },
      { name: 'hatay', id: 31 },
      { name: 'isparta', id: 32 },
      { name: 'mersin', id: 33 },
      { name: 'istanbul', id: 34 },
      { name: 'izmir', id: 35 },
      { name: 'kars', id: 36 },
      { name: 'kastamonu', id: 37 },
      { name: 'kayseri', id: 38 },
      { name: 'kirklareli', id: 39 },
      { name: 'kirsehir', id: 40 },
      { name: 'kocaeli', id: 41 },
      { name: 'konya', id: 42 },
      { name: 'kutahya', id: 43 },
      { name: 'malatya', id: 44 },
      { name: 'manisa', id: 45 },
      { name: 'kahramanmaras', id: 46 },
      { name: 'mardin', id: 47 },
      { name: 'mugla', id: 48 },
      { name: 'mus', id: 49 },
      { name: 'nevsehir', id: 50 },
      { name: 'nigde', id: 51 },
      { name: 'ordu', id: 52 },
      { name: 'rize', id: 53 },
      { name: 'sakarya', id: 54 },
      { name: 'samsun', id: 55 },
      { name: 'siirt', id: 56 },
      { name: 'sinop', id: 57 },
      { name: 'sivas', id: 58 },
      { name: 'tekirdag', id: 59 },
      { name: 'tokat', id: 60 },
      { name: 'trabzon', id: 61 },
      { name: 'tunceli', id: 62 },
      { name: 'sanliurfa', id: 63 },
      { name: 'usak', id: 64 },
      { name: 'van', id: 65 },
      { name: 'yozgat', id: 66 },
      { name: 'zonguldak', id: 67 },
      { name: 'aksaray', id: 68 },
      { name: 'bayburt', id: 69 },
      { name: 'karaman', id: 70 },
      { name: 'kirikkale', id: 71 },
      { name: 'batman', id: 72 },
      { name: 'sirnak', id: 73 },
      { name: 'bartin', id: 74 },
      { name: 'ardahan', id: 75 },
      { name: 'igdir', id: 76 },
      { name: 'yalova', id: 77 },
      { name: 'karabuk', id: 78 },
      { name: 'kilis', id: 79 },
      { name: 'osmaniye', id: 80 },
      { name: 'duzce', id: 81 },
    ];

    this.districts = [
      // adana
      [
        { name: 'seyhan', id: 1 },
        { name: 'yuregir', id: 2 },
        { name: 'ceyhan', id: 3 },
        { name: 'cukurova', id: 4 },
        { name: 'karaisali', id: 5 },
        { name: 'saricam', id: 6 },
        { name: 'pozanti', id: 7 },
        { name: 'aladag', id: 8 },
        { name: 'feke', id: 9 },
        { name: 'saimbeyli', id: 10 },
        { name: 'imamoglu', id: 11 },
        { name: 'tufanbeyli', id: 12 },
        { name: 'yumurtalik', id: 13 },
      ],

      // adiyaman
      [
        { name: 'merkez', id: 14 },
        { name: 'besni', id: 15 },
        { name: 'celikhan', id: 16 },
        { name: 'gerger', id: 17 },
        { name: 'golbasi', id: 18 },
        { name: 'kahta', id: 19 },
        { name: 'samsat', id: 20 },
        { name: 'sincik', id: 21 },
        { name: 'tut', id: 22 },
      ],

      // afyonkarahisar
      [
        { name: 'basmakci', id: 23 },
        { name: 'bayat', id: 24 },
        { name: 'bolvadin', id: 25 },
        { name: 'cay', id: 26 },
        { name: 'cobanlar', id: 27 },
        { name: 'dazkiri', id: 28 },
        { name: 'dinar', id: 29 },
        { name: 'emirdag', id: 30 },
        { name: 'evciler', id: 31 },
        { name: 'hocalar', id: 32 },
        { name: 'ihsaniye', id: 33 },
        { name: 'iscehisar', id: 34 },
        { name: 'kiziloren', id: 35 },
        { name: 'sandikli', id: 36 },
        { name: 'sinanpasa', id: 37 },
        { name: 'sultandagi', id: 38 },
        { name: 'suhut', id: 39 },
      ],

      // agri
      [
        { name: 'diyadin', id: 40 },
        { name: 'dogubeyazit', id: 41 },
        { name: 'eleskirt', id: 42 },
        { name: 'hamur', id: 43 },
        { name: 'patnos', id: 44 },
        { name: 'taslicay', id: 45 },
        { name: 'tutak', id: 46 },
      ],

      // amasya
      [
        { name: 'gorele', id: 47 },
        { name: 'suluova', id: 48 },
        { name: 'tasova', id: 49 },
        { name: 'bogazkale', id: 50 },
        { name: 'merkez', id: 51 },
        { name: 'gumushacikoy', id: 52 },
        { name: 'havza', id: 53 },
        { name: 'ilgin', id: 54 },
        { name: 'sarikaya', id: 55 },
      ],

      // ankara
      [
        { name: 'merkez', id: 56 },
        { name: 'altindag', id: 57 },
        { name: 'polatli', id: 58 },
        { name: 'yenimahalle', id: 59 },
        { name: 'baskent', id: 60 },
        { name: 'mamak', id: 61 },
        { name: 'kecioren', id: 62 },
        { name: 'sincan', id: 63 },
        { name: 'cubuk', id: 64 },
        { name: 'golbasi', id: 65 },
        { name: 'etimesgut', id: 66 },
        { name: 'golkoy', id: 67 },
      ],

      // antalya
      [
        { name: 'akseki', id: 68 },
        { name: 'aksu', id: 69 },
        { name: 'alanya', id: 70 },
        { name: 'demre', id: 71 },
        { name: 'dosemealti', id: 72 },
        { name: 'elmali', id: 73 },
        { name: 'finike', id: 74 },
        { name: 'gazipasa', id: 75 },
        { name: 'gundogmus', id: 76 },
        { name: 'ibradi', id: 77 },
        { name: 'kas', id: 78 },
        { name: 'kemer', id: 79 },
        { name: 'kepez', id: 80 },
        { name: 'konyaalti', id: 81 },
        { name: 'korkuteli', id: 82 },
        { name: 'kumluca', id: 83 },
        { name: 'manavgat', id: 84 },
        { name: 'muratpasa', id: 85 },
        { name: 'serik', id: 86 },
      ],

      // artvin
      [
        { name: 'ardanuc', id: 87 },
        { name: 'arhavi', id: 88 },
        { name: 'borcka', id: 89 },
        { name: 'hopa', id: 90 },
        { name: 'murgul', id: 91 },
        { name: 'savsat', id: 92 },
        { name: 'yusufeli', id: 93 },
      ],
      [
        { name: 'bozdogan', id: 94 },
        { name: 'buharkent', id: 95 },
        { name: 'cine', id: 96 },
        { name: 'didim', id: 97 },
        { name: 'efeler', id: 98 },
        { name: 'germencik', id: 99 },
        { name: 'incirliova', id: 100 },
        { name: 'karacasu', id: 101 },
        { name: 'kocarli', id: 102 },
        { name: 'kosk', id: 103 },
        { name: 'kuyucak', id: 104 },
        { name: 'nazilli', id: 105 },
        { name: 'soke', id: 106 },
        { name: 'sultanhisar', id: 107 },
        { name: 'yenipazar', id: 108 },
      ],
      [
        { name: 'altieylul', id: 109 },
        { name: 'ayvalik', id: 110 },
        { name: 'bandirma', id: 111 },
        { name: 'bigadic', id: 112 },
        { name: 'burhaniye', id: 113 },
        { name: 'dursunbey', id: 114 },
        { name: 'edremit', id: 115 },
        { name: 'erdek', id: 116 },
        { name: 'gomec', id: 117 },
        { name: 'gonen', id: 118 },
        { name: 'havran', id: 119 },
        { name: 'ivrindi', id: 120 },
        { name: 'karesi', id: 121 },
        { name: 'kepsut', id: 122 },
        { name: 'manyas', id: 123 },
        { name: 'marmara', id: 124 },
        { name: 'savastepe', id: 125 },
        { name: 'sindirgi', id: 126 },
        { name: 'susurluk', id: 127 },
      ],
      [
        { name: 'bozuyuk', id: 128 },
        { name: 'golpazari', id: 129 },
        { name: 'inhisar', id: 130 },
        { name: 'osmaneli', id: 131 },
        { name: 'pazaryeri', id: 132 },
        { name: 'sogut', id: 133 },
        { name: 'yenipazar', id: 134 },
      ],
      [
        { name: 'adakli', id: 135 },
        { name: 'genc', id: 136 },
        { name: 'karliova', id: 137 },
        { name: 'kigi', id: 138 },
        { name: 'solhan', id: 139 },
        { name: 'yayladere', id: 140 },
        { name: 'yedisu', id: 141 },
      ],
      [
        { name: 'adalet', id: 142 },
        { name: 'ahlat', id: 143 },
        { name: 'guroymak', id: 144 },
        { name: 'hizan', id: 145 },
        { name: 'mutki', id: 146 },
        { name: 'tatvan', id: 147 },
      ],
      [
        { name: 'dortdivan', id: 148 },
        { name: 'goynuk', id: 149 },
        { name: 'kibriscik', id: 150 },
        { name: 'mengen', id: 151 },
        { name: 'mudurnu', id: 152 },
        { name: 'seben', id: 153 },
        { name: 'gerede', id: 154 },
        { name: 'yenicağa', id: 155 },
      ],
      [
        { name: 'aglasun', id: 156 },
        { name: 'altinyayla', id: 157 },
        { name: 'bucak', id: 158 },
        { name: 'cavdir', id: 159 },
        { name: 'celtikci', id: 160 },
        { name: 'golhisar', id: 161 },
        { name: 'karamanli', id: 162 },
        { name: 'kemer', id: 163 },
        { name: 'tefenni', id: 164 },
        { name: 'yesilova', id: 165 },
      ],
      [
        { name: 'buyukorhan', id: 166 },
        { name: 'gemlik', id: 167 },
        { name: 'gursu', id: 168 },
        { name: 'harmanck', id: 169 },
        { name: 'inegol', id: 170 },
        { name: 'iznik', id: 171 },
        { name: 'karacabey', id: 172 },
        { name: 'keles', id: 173 },
        { name: 'kestel', id: 174 },
        { name: 'mudanya', id: 175 },
        { name: 'mustafakemalpasa', id: 176 },
        { name: 'nilufer', id: 177 },
        { name: 'orhaneli', id: 178 },
        { name: 'orhangazi', id: 179 },
        { name: 'osmangazi', id: 180 },
        { name: 'yenisehir', id: 181 },
        { name: 'yildirim', id: 182 },
      ],
      [
        { name: 'biga', id: 183 },
        { name: 'bozcaada', id: 184 },
        { name: 'gokceada', id: 185 },
        { name: 'lapseki', id: 186 },
        { name: 'can', id: 187 },
        { name: 'dardanel', id: 188 },
        { name: 'ezine', id: 189 },
        { name: 'gelibolu', id: 190 },
        { name: 'haberler', id: 191 },
        { name: 'merkez', id: 192 },
        { name: 'troy', id: 193 },
      ],
      [
        { name: 'atkaracalar', id: 194 },
        { name: 'bayramoren', id: 195 },
        { name: 'camsit', id: 196 },
        { name: 'korgun', id: 197 },
        { name: 'kursunlu', id: 198 },
        { name: 'sarayduzu', id: 199 },
        { name: 'cankiri', id: 200 },
      ],
      [
        { name: 'alaca', id: 201 },
        { name: 'bayat', id: 202 },
        { name: 'boğazkale', id: 203 },
        { name: 'dodurga', id: 204 },
        { name: 'eskikoy', id: 205 },
        { name: 'hitit', id: 206 },
        { name: 'kargi', id: 207 },
        { name: 'lacin', id: 208 },
        { name: 'mecitozu', id: 209 },
        { name: 'omerler', id: 210 },
        { name: 'sungurlu', id: 211 },
        { name: 'uzunbey', id: 212 },
        { name: 'corum', id: 213 },
      ],
      [
        { name: 'acipayam', id: 214 },
        { name: 'buldan', id: 215 },
        { name: 'cakirbeyli', id: 216 },
        { name: 'cal', id: 217 },
        { name: 'dulkadiroglu', id: 218 },
        { name: 'gure', id: 219 },
        { name: 'honaz', id: 220 },
        { name: 'serinhisar', id: 221 },
        { name: 'tavas', id: 222 },
        { name: 'merkezefendi', id: 223 },
        { name: 'pamukkale', id: 224 },
      ],
      [
        { name: 'bağlar', id: 225 },
        { name: 'bismil', id: 226 },
        { name: 'cermik', id: 227 },
        { name: 'cinar', id: 228 },
        { name: 'dien', id: 229 },
        { name: 'ergani', id: 230 },
        { name: 'hilvan', id: 231 },
        { name: 'kayapinar', id: 232 },
        { name: 'kulp', id: 233 },
        { name: 'lio', id: 234 },
        { name: 'savur', id: 235 },
        { name: 'silvan', id: 236 },
        { name: 'diyarbakir', id: 237 },
      ],
      [
        { name: 'kapikule', id: 238 },
        { name: 'luleburgaz', id: 239 },
        { name: 'edirne merkez', id: 240 },
        { name: 'uzunkopru', id: 241 },
        { name: 'havsa', id: 242 },
        { name: 'mimar sinan', id: 243 },
        { name: 'pehlivankoy', id: 244 },
        { name: 'suloğlu', id: 245 },
        { name: 'merkez', id: 246 },
        { name: 'kesan', id: 247 },
      ],
      [
        { name: 'alacakaya', id: 248 },
        { name: 'baskil', id: 249 },
        { name: 'karakocan', id: 250 },
        { name: 'keban', id: 251 },
        { name: 'maden', id: 252 },
        { name: 'palu', id: 253 },
        { name: 'sivrice', id: 254 },
        { name: 'gezin', id: 255 },
        { name: 'merkez', id: 256 },
      ],
      [
        { name: 'cayirli', id: 257 },
        { name: 'divriği', id: 258 },
        { name: 'kemaliye', id: 259 },
        { name: 'tercan', id: 260 },
        { name: 'urgup', id: 261 },
        { name: 'erzincan merkez', id: 262 },
        { name: 'cayirli', id: 263 },
        { name: 'okul', id: 264 },
      ],
      [
        { name: 'aziziye', id: 265 },
        { name: 'narman', id: 266 },
        { name: 'palandoken', id: 267 },
        { name: 'horasan', id: 268 },
        { name: 'kars', id: 269 },
        { name: 'pasinler', id: 270 },
        { name: 'tortum', id: 271 },
        { name: 'yakutiye', id: 272 },
        { name: 'cat', id: 273 },
        { name: 'oltu', id: 274 },
        { name: 'tortum', id: 275 },
        { name: 'uzumcu', id: 276 },
      ],
      [
        { name: 'battalgazi', id: 277 },
        { name: 'cukurhisar', id: 278 },
        { name: 'eskisehir merkez', id: 279 },
        { name: 'germiyanoğlu', id: 280 },
        { name: 'inonu', id: 281 },
        { name: 'odunpazari', id: 282 },
        { name: 'sivrihisar', id: 283 },
        { name: 'tepebasi', id: 284 },
      ],
      [
        { name: 'sahinbey', id: 285 },
        { name: 'oğuzeli', id: 286 },
        { name: 'nizip', id: 287 },
        { name: 'araban', id: 288 },
        { name: 'yavuzeli', id: 289 },
        { name: 'alicankaya', id: 290 },
        { name: 'vallahi', id: 291 },
        { name: 'karkamis', id: 292 },
        { name: 'gaziantep merkez', id: 293 },
        { name: 'zeytinlik', id: 294 },
        { name: 'sahipata', id: 295 },
        { name: 'nizip', id: 296 },
      ],
      [
        { name: 'alucra', id: 297 },
        { name: 'bulancak', id: 298 },
        { name: 'camoluk', id: 299 },
        { name: 'dereli', id: 300 },
        { name: 'gorele', id: 301 },
        { name: 'kesap', id: 302 },
        { name: 'piraziz', id: 303 },
        { name: 'sebinkarahisar', id: 304 },
        { name: 'eynesil', id: 305 },
        { name: 'giresun merkez', id: 306 },
      ],
      [
        { name: 'kelkit', id: 307 },
        { name: 'torul', id: 308 },
        { name: 'kurtun', id: 309 },
        { name: 'merkez', id: 310 },
        { name: 'siran', id: 311 },
        { name: 'ozdemir', id: 312 },
        { name: 'gumushane merkez', id: 313 },
      ],
      [
        { name: 'semdinli', id: 314 },
        { name: 'yuksekova', id: 315 },
        { name: 'cukurca', id: 316 },
        { name: 'merkez', id: 317 },
      ],
      [
        { name: 'antakya', id: 318 },
        { name: 'defne', id: 319 },
        { name: 'samandağ', id: 320 },
        { name: 'dortyol', id: 321 },
        { name: 'erzin', id: 322 },
        { name: 'hassa', id: 323 },
        { name: 'ismailiye', id: 324 },
        { name: 'kaman', id: 325 },
        { name: 'reyhanli', id: 326 },
        { name: 'yalnizca', id: 327 },
        { name: 'payas', id: 328 },
        { name: 'altinozu', id: 329 },
      ],
      [
        { name: 'gonen', id: 330 },
        { name: 'yalvac', id: 331 },
        { name: 'egirdir', id: 332 },
        { name: 'senirkent', id: 333 },
        { name: 'keciborlu', id: 334 },
        { name: 'sutculer', id: 335 },
        { name: 'uluborlu', id: 336 },
        { name: 'merkez', id: 337 },
      ],
      [
        { name: 'akdeniz', id: 338 },
        { name: 'toroslar', id: 339 },
        { name: 'mezitli', id: 340 },
        { name: 'tarsus', id: 341 },
        { name: 'erdemli', id: 342 },
        { name: 'silifke', id: 343 },
        { name: 'anamur', id: 344 },
        { name: 'mut', id: 345 },
        { name: 'gulnar', id: 346 },
        { name: 'camliyayla', id: 347 },
        { name: 'karacahisar', id: 348 },
      ],

      // istanbul
      [
        { name: 'adalar', id: 349 },
        { name: 'arnavutkoy', id: 350 },
        { name: 'atasehir', id: 351 },
        { name: 'avcilar', id: 352 },
        { name: 'bagcilar', id: 353 },
        { name: 'bahcelievler', id: 354 },
        { name: 'bakirkoy', id: 355 },
        { name: 'basaksehir', id: 356 },
        { name: 'bayrampasa', id: 357 },
        { name: 'besiktas', id: 358 },
        { name: 'beykoz', id: 359 },
        { name: 'beylikduzu', id: 360 },
        { name: 'beyoglu', id: 361 },
        { name: 'buyukcekmece', id: 362 },
        { name: 'cekmekoy', id: 363 },
        { name: 'esenler', id: 364 },
        { name: 'esenyurt', id: 365 },
        { name: 'eyupsultan', id: 366 },
        { name: 'fatih', id: 367 },
        { name: 'gaziosmanpasa', id: 368 },
        { name: 'gungoren', id: 369 },
        { name: 'kadikoy', id: 370 },
        { name: 'kagithane', id: 371 },
        { name: 'kartal', id: 372 },
        { name: 'kucukcekmece', id: 373 },
        { name: 'maltepe', id: 374 },
        { name: 'pendik', id: 375 },
        { name: 'sancaktepe', id: 376 },
        { name: 'sariyer', id: 377 },
        { name: 'silivri', id: 378 },
        { name: 'sultanbeyli', id: 379 },
        { name: 'sultangazi', id: 380 },
        { name: 'sile', id: 381 },
        { name: 'sisli', id: 382 },
        { name: 'tuzla', id: 383 },
        { name: 'umraniye', id: 384 },
        { name: 'uskudar', id: 385 },
        { name: 'zeytinburnu', id: 386 },
      ],

      // izmir
      [
        { name: 'balcova', id: 387 },
        { name: 'bayindir', id: 388 },
        { name: 'bergama', id: 389 },
        { name: 'beydag', id: 390 },
        { name: 'bornova', id: 391 },
        { name: 'buca', id: 392 },
        { name: 'cesme', id: 393 },
        { name: 'cigli', id: 394 },
        { name: 'dikili', id: 395 },
        { name: 'foca', id: 396 },
        { name: 'gaziemir', id: 397 },
        { name: 'guzelbahce', id: 398 },
        { name: 'karaburun', id: 399 },
        { name: 'karabaglar', id: 400 },
        { name: 'karsiyaka', id: 401 },
        { name: 'kemalpasa', id: 402 },
        { name: 'kinik', id: 403 },
        { name: 'kiraz', id: 404 },
        { name: 'konak', id: 405 },
        { name: 'menderes', id: 406 },
        { name: 'menemen', id: 407 },
        { name: 'narlidere', id: 408 },
        { name: 'odemis', id: 409 },
        { name: 'seferihisar', id: 410 },
        { name: 'selcuk', id: 411 },
        { name: 'tire', id: 412 },
        { name: 'torbali', id: 413 },
        { name: 'urla', id: 414 },
      ],
      [
        { name: 'ardahan', id: 415 },
        { name: 'selim', id: 416 },
        { name: 'susuz', id: 417 },
        { name: 'kağizman', id: 418 },
        { name: 'cildir', id: 419 },
        { name: 'merkez', id: 420 },
      ],
      [
        { name: 'ademcik', id: 421 },
        { name: 'taskopru', id: 422 },
        { name: 'kuracay', id: 423 },
        { name: 'devrekani', id: 424 },
        { name: 'pinarbasi', id: 425 },
        { name: 'kastamonu merkez', id: 426 },
        { name: 'seydiler', id: 427 },
        { name: 'daday', id: 428 },
        { name: 'ağli', id: 429 },
        { name: 'hanonu', id: 430 },
      ],
      [
        { name: 'melikgazi', id: 431 },
        { name: 'kocasinan', id: 432 },
        { name: 'talas', id: 433 },
        { name: 'develi', id: 434 },
        { name: 'eri̇ci̇yes', id: 435 },
        { name: 'bunyan', id: 436 },
        { name: 'hacilar', id: 437 },
        { name: 'pinarbasi', id: 438 },
        { name: 'tomarza', id: 439 },
        { name: 'sarioğlan', id: 440 },
        { name: 'ozel', id: 441 },
      ],
      [
        { name: 'merkez', id: 442 },
        { name: 'babaeski', id: 443 },
        { name: 'luleburgaz', id: 444 },
        { name: 'vize', id: 445 },
        { name: 'pinarhisar', id: 446 },
        { name: 'demirtas', id: 447 },
      ],
      [
        { name: 'merkez', id: 448 },
        { name: 'akpinar', id: 449 },
        { name: 'mucur', id: 450 },
        { name: 'kaman', id: 451 },
        { name: 'cicekdaği', id: 452 },
        { name: 'heroğlu', id: 453 },
      ],
      [
        { name: 'izmit', id: 454 },
        { name: 'gebze', id: 455 },
        { name: 'derince', id: 456 },
        { name: 'golcuk', id: 457 },
        { name: 'kandira', id: 458 },
        { name: 'dilovasi', id: 459 },
        { name: 'cayirova', id: 460 },
        { name: 'basiskele', id: 461 },
        { name: 'sekapark', id: 462 },
        { name: 'turkovac', id: 463 },
      ],
      [
        { name: 'meram', id: 464 },
        { name: 'selcuklu', id: 465 },
        { name: 'karatay', id: 466 },
        { name: 'ilgin', id: 467 },
        { name: 'aksehir', id: 468 },
        { name: 'ereğli', id: 469 },
        { name: 'sarayonu', id: 470 },
        { name: 'cihanbeyli', id: 471 },
        { name: 'tuzlukcu', id: 472 },
        { name: 'huyuk', id: 473 },
        { name: 'cumra', id: 474 },
        { name: 'karapinar', id: 475 },
        { name: 'akoren', id: 476 },
        { name: 'doğanhisar', id: 477 },
        { name: 'derebucak', id: 478 },
        { name: 'beysehir', id: 479 },
        { name: 'guneysinir', id: 480 },
        { name: 'altinekin', id: 481 },
      ],
      [
        { name: 'merkez', id: 482 },
        { name: 'domanic', id: 483 },
        { name: 'gediz', id: 484 },
        { name: 'tavsanli', id: 485 },
        { name: 'simav', id: 486 },
        { name: 'hisarcik', id: 487 },
        { name: 'saphane', id: 488 },
        { name: 'cavdarhisar', id: 489 },
      ],
      [
        { name: 'merkez', id: 490 },
        { name: 'battalgazi', id: 491 },
        { name: 'yesilyurt', id: 492 },
        { name: 'akcadağ', id: 493 },
        { name: 'doğanyol', id: 494 },
        { name: 'puturge', id: 495 },
        { name: 'darende', id: 496 },
        { name: 'hozat', id: 497 },
        { name: 'malatya', id: 498 },
        { name: 'sancaktepe', id: 499 },
      ],
      [
        { name: 'merkez', id: 500 },
        { name: 'akhisar', id: 501 },
        { name: 'salihli', id: 502 },
        { name: 'turgutlu', id: 503 },
        { name: 'demirtas', id: 504 },
        { name: 'gordes', id: 505 },
        { name: 'soma', id: 506 },
        { name: 'kula', id: 507 },
        { name: 'saruhanli', id: 508 },
        { name: 'bayindir', id: 509 },
        { name: 'sehzadeler', id: 510 },
      ],
      [
        { name: 'merkez', id: 511 },
        { name: 'dulkadiroğlu', id: 512 },
        { name: 'ondokuzmayis', id: 513 },
        { name: 'afsin', id: 514 },
        { name: 'elbistan', id: 515 },
        { name: 'goksun', id: 516 },
        { name: 'pazarcik', id: 517 },
        { name: ' Turkoğlu', id: 518 },
        { name: 'necmettin erbakan', id: 519 },
      ],
      [
        { name: 'merkez', id: 520 },
        { name: 'derik', id: 521 },
        { name: 'kiziltepe', id: 522 },
        { name: 'nusaybin', id: 523 },
        { name: 'savur', id: 524 },
        { name: 'midyat', id: 525 },
        { name: 'dargecit', id: 526 },
        { name: 'omerli', id: 527 },
        { name: 'mazidaği', id: 528 },
      ],
      [
        { name: 'merkez', id: 529 },
        { name: 'bodrum', id: 530 },
        { name: 'dalaman', id: 531 },
        { name: 'datca', id: 532 },
        { name: 'fethiye', id: 533 },
        { name: 'marmaris', id: 534 },
        { name: 'orkun', id: 535 },
        { name: 'koyceğiz', id: 536 },
        { name: 'uzerlik', id: 537 },
        { name: 'dalyan', id: 538 },
        { name: 'sasli', id: 539 },
      ],
      [
        { name: 'merkez', id: 540 },
        { name: 'bulanik', id: 541 },
        { name: 'malazgirt', id: 542 },
        { name: 'haskoy', id: 543 },
        { name: 'varto', id: 544 },
      ],
      [
        { name: 'merkez', id: 545 },
        { name: 'gulsehir', id: 546 },
        { name: 'hacibektas', id: 547 },
        { name: 'avanos', id: 548 },
        { name: 'derinkuyu', id: 549 },
        { name: 'urgup', id: 550 },
      ],
      [
        { name: 'merkez', id: 551 },
        { name: 'bor', id: 552 },
        { name: 'ulas', id: 553 },
        { name: 'niğde', id: 554 },
        { name: 'camardi', id: 555 },
        { name: 'dumanli', id: 556 },
      ],
      [
        { name: 'merkez', id: 557 },
        { name: 'unye', id: 558 },
        { name: 'fatsa', id: 559 },
        { name: 'golkoy', id: 560 },
        { name: 'gulyali', id: 561 },
        { name: 'kabaduz', id: 562 },
        { name: 'persembe', id: 563 },
        { name: 'aybasti', id: 564 },
        { name: 'caybasi', id: 565 },
        { name: 'kumru', id: 566 },
        { name: 'altinordu', id: 567 },
      ],
      [
        { name: 'rize', id: 568 },
        { name: 'merkez', id: 569 },
        { name: 'artvin', id: 570 },
        { name: 'cayeli', id: 571 },
        { name: 'pazar', id: 572 },
        { name: 'camlihemsin', id: 573 },
        { name: 'hekimhan', id: 574 },
        { name: 'derepazari', id: 575 },
        { name: 'findikli', id: 576 },
        { name: 'hayrat', id: 577 },
        { name: 'uzundere', id: 578 },
        { name: 'arman', id: 579 },
      ],
      [
        { name: 'merkez', id: 580 },
        { name: 'adapazari', id: 581 },
        { name: 'serdivan', id: 582 },
        { name: 'karasu', id: 583 },
        { name: 'akcakoca', id: 584 },
        { name: 'kocaali', id: 585 },
        { name: 'sapanca', id: 586 },
        { name: 'hendek', id: 587 },
        { name: 'pamukova', id: 588 },
        { name: 'tuzla', id: 589 },
        { name: 'geyve', id: 590 },
      ],
      [
        { name: 'merkez', id: 591 },
        { name: 'bafra', id: 592 },
        { name: 'salas', id: 593 },
        { name: 'vezirkopru', id: 594 },
        { name: 'atakum', id: 595 },
        { name: '19-mayis', id: 596 },
        { name: 'ilkadim', id: 597 },
        { name: 'turkeli', id: 598 },
        { name: 'aydinlik', id: 599 },
        { name: 'canik', id: 600 },
        { name: 'ladik', id: 601 },
      ],
      [
        { name: 'merkez', id: 602 },
        { name: 'tillo', id: 603 },
        { name: 'pervari', id: 604 },
        { name: 'sirvan', id: 605 },
        { name: 'kurtalan', id: 606 },
        { name: 'savur', id: 607 },
        { name: 'gokce', id: 608 },
      ],
      [
        { name: 'merkez', id: 609 },
        { name: 'boyabat', id: 610 },
        { name: 'durağan', id: 611 },
        { name: 'soray', id: 612 },
        { name: 'erfelek', id: 613 },
        { name: 'turkeli', id: 614 },
        { name: 'akcakoca', id: 615 },
      ],
      [
        { name: 'merkez', id: 616 },
        { name: 'gurun', id: 617 },
        { name: 'zara', id: 618 },
        { name: 'kangal', id: 619 },
        { name: 'divriği', id: 620 },
        { name: 'uchisar', id: 621 },
        { name: 'susehri', id: 622 },
        { name: 'reyhan', id: 623 },
        { name: 'huzur', id: 624 },
      ],
      [
        { name: 'merkez', id: 625 },
        { name: 'corlu', id: 626 },
        { name: 'kapakli', id: 627 },
        { name: 'malkara', id: 628 },
        { name: 'saray', id: 629 },
        { name: 'hayrabolu', id: 630 },
        { name: 'ergene', id: 631 },
      ],
      [
        { name: 'merkez', id: 632 },
        { name: 'niksar', id: 633 },
        { name: 'turhal', id: 634 },
        { name: 'resadiye', id: 635 },
        { name: 'zile', id: 636 },
        { name: 'erbaa', id: 637 },
        { name: 'basciftlik', id: 638 },
      ],
      [
        { name: 'merkez', id: 639 },
        { name: 'akcaabat', id: 640 },
        { name: 'surmene', id: 641 },
        { name: 'arakli', id: 642 },
        { name: 'caykara', id: 643 },
        { name: 'macka', id: 644 },
        { name: 'of', id: 645 },
        { name: 'urunlu', id: 646 },
        { name: 'besikduzu', id: 647 },
        { name: 'duzkoy', id: 648 },
        { name: 'tonya', id: 649 },
        { name: 'vakfikebir', id: 650 },
        { name: 'yomra', id: 651 },
      ],
      [
        { name: 'merkez', id: 652 },
        { name: 'pertek', id: 653 },
        { name: 'nazimiye', id: 654 },
        { name: 'pulumur', id: 655 },
        { name: 'hozat', id: 656 },
        { name: 'dumlu', id: 657 },
        { name: 'cemisgezek', id: 658 },
      ],
      [
        { name: 'merkez', id: 659 },
        { name: 'haliliye', id: 660 },
        { name: 'eyyubiye', id: 661 },
        { name: 'viransehir', id: 662 },
        { name: 'birecik', id: 663 },
        { name: 'bozova', id: 664 },
        { name: 'ceylanpinar', id: 665 },
        { name: 'siverek', id: 666 },
        { name: 'harran', id: 667 },
        { name: 'kulu', id: 668 },
      ],
      [
        { name: 'merkez', id: 669 },
        { name: 'banaz', id: 670 },
        { name: 'sivasli', id: 671 },
        { name: 'ulubey', id: 672 },
        { name: 'karahalli', id: 673 },
        { name: 'esme', id: 674 },
      ],
      [
        { name: 'merkez', id: 675 },
        { name: 'edremit', id: 676 },
        { name: 'gevas', id: 677 },
        { name: 'tusba', id: 678 },
        { name: 'caldiran', id: 679 },
        { name: 'bahcesaray', id: 680 },
        { name: 'ozpinar', id: 681 },
        { name: 'baskale', id: 682 },
        { name: 'hakkari', id: 683 },
        { name: 'semdinli', id: 684 },
      ],
      [
        { name: 'merkez', id: 685 },
        { name: 'sorgun', id: 686 },
        { name: 'akdağmadeni', id: 687 },
        { name: 'boğazliyan', id: 688 },
        { name: 'cekerek', id: 689 },
        { name: 'kadirli', id: 690 },
        { name: 'yerkoy', id: 691 },
        { name: 'ulas', id: 692 },
        { name: 'aydincik', id: 693 },
      ],
      [
        { name: 'merkez', id: 694 },
        { name: 'ereğli', id: 695 },
        { name: 'devrek', id: 696 },
        { name: 'kozlu', id: 697 },
        { name: 'gokcebey', id: 698 },
        { name: 'caycuma', id: 699 },
        { name: 'alapli', id: 700 },
      ],
      [
        { name: 'merkez', id: 701 },
        { name: 'gulağac', id: 702 },
        { name: 'hacibektas', id: 703 },
        { name: 'eskil', id: 704 },
        { name: 'kizilkaya', id: 705 },
        { name: 'sariyahsi', id: 706 },
      ],
      [
        { name: 'merkez', id: 707 },
        { name: 'demirtas', id: 708 },
        { name: 'yolu', id: 709 },
        { name: 'harmanli', id: 710 },
        { name: 'goygol', id: 711 },
      ],
      [
        { name: 'merkez', id: 712 },
        { name: 'ermenek', id: 713 },
        { name: 'sariveliler', id: 714 },
        { name: 'akcasehir', id: 715 },
        { name: 'basyayla', id: 716 },
      ],
      [
        { name: 'merkez', id: 717 },
        { name: 'balic', id: 718 },
        { name: 'delice', id: 719 },
        { name: 'karakecili', id: 720 },
        { name: 'yahsihan', id: 721 },
      ],
      [
        { name: 'merkez', id: 722 },
        { name: 'hasankeyf', id: 723 },
        { name: 'gercus', id: 724 },
        { name: 'besiri', id: 725 },
        { name: 'sason', id: 726 },
        { name: 'balpinar', id: 727 },
      ],
      [
        { name: 'merkez', id: 728 },
        { name: 'cizre', id: 729 },
        { name: 'silopi', id: 730 },
        { name: 'beytussebap', id: 731 },
        { name: 'idil', id: 732 },
        { name: 'guclukonak', id: 733 },
        { name: 'uludere', id: 734 },
      ],
      [
        { name: 'merkez', id: 735 },
        { name: 'ağdaci', id: 736 },
        { name: 'kurucasile', id: 737 },
        { name: 'ulus', id: 738 },
        { name: 'kamisli', id: 739 },
      ],
      [
        { name: 'merkez', id: 740 },
        { name: 'camlihemsin', id: 741 },
        { name: 'hanak', id: 742 },
        { name: 'posof', id: 743 },
        { name: 'gole', id: 744 },
      ],
      [
        { name: 'merkez', id: 745 },
        { name: 'aralik', id: 746 },
        { name: 'tuzluca', id: 747 },
        { name: 'karacoban', id: 748 },
      ],
      [
        { name: 'merkez', id: 749 },
        { name: 'altinova', id: 750 },
        { name: 'ciftlikkoy', id: 751 },
        { name: 'termal', id: 752 },
        { name: 'aramaya', id: 753 },
      ],
      [
        { name: 'merkez', id: 754 },
        { name: 'safranbolu', id: 755 },
        { name: 'eflani', id: 756 },
        { name: 'ovacik', id: 757 },
        { name: 'yenice', id: 758 },
      ],
      [
        { name: 'merkez', id: 759 },
        { name: 'pinarbasi', id: 760 },
        { name: 'musabeyli', id: 761 },
        { name: 'polateli', id: 762 },
      ],
      [
        { name: 'merkez', id: 763 },
        { name: 'duzici', id: 764 },
        { name: 'toprakkale', id: 765 },
        { name: 'kadirli', id: 766 },
        { name: 'bahce', id: 767 },
        { name: 'sumbas', id: 768 },
      ],
      [
        { name: 'merkez', id: 769 },
        { name: 'akcakoca', id: 770 },
        { name: 'yigilca', id: 771 },
        { name: 'golyaka', id: 772 },
        { name: 'cumayeri', id: 773 },
        { name: 'cilimli', id: 774 },
      ],
    ];

    this.neighbourhoods = [
      // adana
      [], // seyhan
      [], // yuregir
      [], // ceyhan
      [], // cukurova
      [], // karaisali
      [], // saricam
      [], // pozanti
      [], // aladag
      [], // feke
      [], // saimbeyli
      [], // imamoglu
      [], // tufanbeyli
      [], // yumurtalik

      // adiyaman
      [], // merkez
      [], // besni
      [], // celikhan
      [], // gerger
      [], // golbasi
      [], // kahta
      [], // samsat
      [], // sincik
      [], // tut

      // afyonkarahisar
      [], // basmakci
      [], // bayat
      [], // bolvadin
      [], // cay
      [], // cobanlar
      [], // dazkiri
      [], // dinar
      [], // emirdag
      [], // evciler
      [], // hocalar
      [], // ihsaniye
      [], // iscehisar
      [], // kiziloren
      [], // sandikli
      [], // sinanpasa
      [], // sultandagi
      [], // suhut

      // agri
      [], // diyadin
      [], // dogubeyazit
      [], // eleskirt
      [], // hamur
      [], // patnos
      [], // taslicay
      [], // tutak

      // amasya
      [], // gorele
      [], // suluova
      [], // tasova
      [], // bogazkale
      [], // merkez
      [], // gumushacikoy
      [], // havza
      [], // ilgin
      [], // sarikaya

      // ankara
      [], // merkez
      [], // altindag
      [], // polatli
      [], // yenimahalle
      [], // baskent
      [], // mamak
      [], // kecioren
      [], // sincan
      [], // cubuk
      [], // golbasi
      [], // etimesgut
      [], // golkoy

      // antalya
      [], // akseki
      [], // aksu
      [], // alanya
      [], // demre
      [], // dosemealti
      [], // elmali
      [], // finike
      [], // gazipasa
      [], // gundogmus
      [], // ibradi
      [], // kas
      [], // kemer
      [], // kepez
      [], // konyaalti
      [], // korkuteli
      [], // kumluca
      [], // manavgat
      [], // muratpasa
      [], // serik

      // artvin
      [], // ardanuc
      [], // arhavi
      [], // borcka
      [], // hopa
      [], // murgul
      [], // savsat
      [], // yusufeli

      // aydin
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
    ];
  }

  async get_settings(credentials: any): Promise<object | null> {
    const settings: string = await this.options.redis.get('settings');
    const result: object = JSON.parse(settings);
    return result;
  }

  async edit_settings(credentials: any): Promise<any> {
    await this.validator.edit_settings(credentials);

    const settings: any | null = JSON.parse(
      await this.options.redis.get('settings')
    );

    await this.options.redis.set('settings', JSON.stringify(settings));

    return settings;
  }

  get_cities(credentials: any): any[] {
    return this.cities;
  }

  get_districts(credentials: any) {
    const index: number = Number(credentials.city) - 1;
    return this.districts[index];
  }

  get_neighbourhoods(credentials: any) {
    const index: number = Number(credentials.district) - 1;
    return this.neighbourhoods[index];
  }
}

export default service_settings_init;
